<?php

/**
 * Implements hook_block_info().
 */
function linebutton_block_info() {
  $blocks = array();
  $blocks['linebutton'] = array(
    'info' => t('LINE it! button'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function linebutton_block_view($delta = '') {
  if ($delta !== 'linebutton') { return array(); }
  if (arg(0) !== 'node' || !is_numeric(arg(1))) { return array(); }
  $nid = arg(1);
  $node = node_load($nid);
  $linkURL = 'http://line.me/R/msg/text/?' . $node->title . ' ' . url('node/' . $node->nid, array('absolute' => TRUE));
  $linkIcon = '<img src="/' . drupal_get_path('module', 'linebutton') . '/linebutton_75x30_en.png" width="75" height="30" alt="LINE 分享" />';
  return array(
    'content' => array(
      '#markup' => l($linkIcon, $linkURL, array('html' => TRUE)),
    ),
  );
}
